const cor = {
    vermelho: "#e4202a",
    marsala: "#771009",
    verde: "#a6e7cf",
    branco: "#ffffff",
    rosa_old: "#c08891",
    rosa_claro: "#fcc8d4",
    azul_marinho: "#000c7a",
    azul_bebe: "#b1ddf6",
    amarelho: "#fefd02",
    off: "#e4d39f",
}


export const lista = [
    {   descricao: "Vestido Floral",
        tamanho: "Tam: 4|6|8|10|12",
        imagem: "./img/ref 201.png",
        preco: "62,90",
        ref: "201",
        cores: []  
    },
    {   descricao: "Vestido Arco Iris",
        tamanho: "Tam: 1|2|3|4",
        imagem: "./img/ref 202.png",
        preco: "59,90",
        ref: "202",
        cores: []  
    },
    {   descricao: "Vestido Floral Azul",
        tamanho: "Tamanho: 4|6|8|10|12",
        imagem: "./img/ref 203.png",
        preco: "61,90",
        ref: "203",
        cores: []  
    },
    {   descricao: "Vestido Moana",
        tamanho: "Tamanho: 1|2|3|4",
        imagem: "./img/ref 204.png",
        preco: "56,90",
        ref: "204",
        cores: []  
    },
    {   descricao: "Vestido Panda",
        tamanho: "Tamanho: 1|2|3|4",
        imagem: "./img/ref 205.png",
        preco: "58,50",
        ref: "205",
        cores: []  
    },
    {   descricao: "Vestido Unicórnio",
        tamanho: "Tamanho: 1|2|3|4",
        imagem: "./img/ref 206.png",
        preco: "59,90",
        ref: "206",
        cores: []  
    },
    {   descricao: "Vestido Coração",
        tamanho: "Tamanho: 1|2|3|4",
        imagem: "./img/ref 207.png",
        preco: "59,90",
        ref: "207",
        cores: []  
    },,
    {   descricao: "Vestido Galinha Pintadinha",
        tamanho: "Tamanho: 1|2|3|4",
        imagem: "./img/ref 208.png",
        preco: "54,90",
        ref: "208",
        cores: []  
    },,
    {   descricao: "Vestido Ariel",
        tamanho: "Tamanho: 1|2|3|4",
        imagem: "./img/ref 209.png",
        preco: "55,90",
        ref: "209",
        cores: []  
    },,
    {   descricao: "Vestido Nuvens",
        tamanho: "Tamanho: 1|2|3|4",
        imagem: "./img/ref 210.png",
        preco: "59,80",
        ref: "210",
        cores: []  
    },
    {   descricao: "Vestido Floral",
        tamanho: "Tamanho: 1|2|3|4",
        imagem: "./img/ref 211.png",
        preco: "59,90",
        ref: "211",
        cores: []  
    },
    {   descricao: "Vestido Floral Regata",
        tamanho: "Tamanho: 4|6|8|10|12",
        imagem: "./img/ref 212.png",
        preco: "52,90",
        ref: "212",
        cores: []  
    },
    {   descricao: "Vestido Floral C/ Manga",
        tamanho: "Tamanho: 4|6|8|10|12",
        imagem: "./img/ref 213.png",
        preco: "52,90",
        ref: "213",
        cores: []  
    },
    {   descricao: "Vestido Tradicional",
        tamanho: "Tamanho: P|M|G",
        imagem: "./img/ref 214.png",
        preco: "39,90",
        ref: "214",
        cores: [cor.vermelho,cor.marsala,cor.verde,cor.branco,cor.rosa_old,cor.rosa_claro,
            cor.azul_marinho,cor.azul_bebe,cor.amarelho,cor.off]  
    },
    {   descricao: "Vestido Borado",
        tamanho: "Tamanho: P|M|G",
        imagem: "./img/ref 215.png",
        preco: "39,90",
        ref: "214",
        cores: [cor.vermelho,cor.marsala,cor.verde,cor.branco,cor.rosa_old,cor.rosa_claro,
            cor.azul_marinho,cor.azul_bebe,cor.amarelho,cor.off]  
    },
    {   descricao: "Vestido Regata",
        tamanho: "Tamanho: P|M|G",
        imagem: "./img/ref 216.png",
        preco: "39,90",
        ref: "797",
        cores: [cor.vermelho,cor.marsala,cor.verde,cor.branco,cor.rosa_old,cor.rosa_claro,
            cor.azul_marinho,cor.azul_bebe,cor.amarelho,cor.off]  
    },
    {   descricao: "Vestido Princesa",
        tamanho: "Tamanho: 1|2|3|4",
        imagem: "./img/ref 807.png",
        preco: "42,90",
        ref: "807",
        cores: []  
    },
    {   descricao: "Vestido Branca de neve",
        tamanho: "Tamanho: 1|2|3|4",
        imagem: "./img/ref 808.png",
        preco: "42,90",
        ref: "808",
        cores: []  
    },,
    {   descricao: "Vestido Unicórnio",
        tamanho: "Tamanho: 1|2|3|4",
        imagem: "./img/ref 818.png",
        preco: "42,90",
        ref: "818",
        cores: []  
    },
    {   descricao: "Vestido Floral",
        tamanho: "Tamanho: 1|2|3|4",
        imagem: "./img/ref 819.png",
        preco: "42,90",
        ref: "819",
        cores: []  
    },
    {   descricao: "Vestido Borboleta",
        tamanho: "Tamanho: P|M|G",
        imagem: "./img/ref 822.png",
        preco: "39,90",
        ref: "822",
        cores: [cor.vermelho,cor.marsala,cor.verde,cor.branco,cor.rosa_old,cor.rosa_claro,
            cor.azul_marinho,cor.azul_bebe,cor.amarelho,cor.off]  
    },
    {   descricao: "Vestido Aniversário",
        tamanho: "Tamanho: 1|2|3|4",
        imagem: "./img/ref 823.png",
        preco: "42,90",
        ref: "823",
        cores: []  
    },
    {   descricao: "Vestido Floral",
        tamanho: "Tamanho: 1|2|3|4",
        imagem: "./img/ref 824.png",
        preco: "42,90",
        ref: "824",
        cores: []  
    },,
    {   descricao: "Vestido Magali",
        tamanho: "Tamanho: 1|2|3|4",
        imagem: "./img/ref 826.png",
        preco: "42,90",
        ref: "826",
        cores: []  
    },,
    {   descricao: "Vestido Laço",
        tamanho: "Tamanho: P|M|G",
        imagem: "./img/ref 829.png",
        preco: "39,90",
        ref: "829",
        cores: []  
    },
    {   descricao: "Vestido Cereja",
        tamanho: "Tamanho: 4|6|8|10|12",
        imagem: "./img/ref 831.png",
        preco: "52,90",
        ref: "831",
        cores: []  
    },
    {   descricao: "Vestido tradicional",
        tamanho: "Tamanho: 4|6|8|10|12",
        imagem: "./img/ref 832.png",
        preco: "52,90",
        ref: "832",
        cores: [cor.vermelho,cor.marsala,cor.verde,cor.branco,cor.rosa_old,cor.rosa_claro,
            cor.azul_marinho,cor.azul_bebe,cor.amarelho,cor.off]  
    },
    {   descricao: "Vestido Borboleta",
        tamanho: "Tamanho: 4|6|8|10|12",
        imagem: "./img/ref 835.png",
        preco: "52,90",
        ref: "835",
        cores: []  
    },
    {   descricao: "Vestido Floral",
        tamanho: "Tamanho: 4|6|8|10|12",
        imagem: "./img/ref 836.png",
        preco: "52,90",
        ref: "836",
        cores: []  
    },
    {   descricao: "Vestido Cupcake",
        tamanho: "Tamanho: 1|2|3|4",
        imagem: "./img/ref 837.png",
        preco: "42,90",
        ref: "837",
        cores: []  
    },
    {   descricao: "Vestido Floral",
        tamanho: "Tamanho: 4|6|8|10|12",
        imagem: "./img/ref 838.png",
        preco: "52,90",
        ref: "838",
        cores: []  
    },
    {   descricao: "Vestido Floral",
        tamanho: "Tamanho: 4|6|8|10|12",
        imagem: "./img/ref 843.png",
        preco: "52,90",
        ref: "843",
        cores: []  
    },
    {   descricao: "Vestido Coração",
        tamanho: "Tamanho: 1|2|3|4",
        imagem: "./img/ref 846.png",
        preco: "42,90",
        ref: "846",
        cores: []  
    },
    {   descricao: "Vestido Love",
        tamanho: "Tamanho: 1|2|3|4",
        imagem: "./img/ref 847.png",
        preco: "42,90",
        ref: "847",
        cores: []  
    },
    {   descricao: "Vestido Urso",
        tamanho: "Tamanho: 1|2|3|4",
        imagem: "./img/ref 848.png",
        preco: "42,90",
        ref: "848",
        cores: []  
    },
  ]